import { ɵBlockUntilFirstOperator } from '@angular/fire';

export class Speaker {

    constructor(
        public id: string = '',
        public name: string = '',
        public position: string = '',
        public qualifications: string[] = [],
        public sector: {
            professionalDriver: boolean,
            professionalRider: boolean,
            plantOperator: boolean,
            conductor: boolean,
            captain: boolean,
            fleetManager: boolean,
            stageManager: boolean,
            stageClerk: boolean,
            courier: boolean,
            driverInstructor: boolean,
            conductorsInstructor: boolean,
            mechanic: boolean,
            civil: boolean,
            urbanPlanner: boolean,
            trainer: boolean,
            leadership: boolean,
            speaker: boolean,
            policy: boolean,
            softwareTelephone: boolean,
            automotive: boolean,
            other: boolean,
        } = {
                professionalDriver: false,
                professionalRider: false,
                plantOperator: false,
                conductor: false,
                captain: false,
                fleetManager: false,
                stageManager: false,
                stageClerk: false,
                courier: false,
                driverInstructor: false,
                conductorsInstructor: false,
                mechanic: false,
                civil: false,
                urbanPlanner: false,
                trainer: false,
                leadership: false,
                speaker: false,
                policy: false,
                softwareTelephone: false,
                automotive: false,
                other: false,
            },
        public otherSector: string = '',
        public bio: string = '',
        public region: string = '',
        public country: string = '',
        public city: string = '',
        public years: string = '',
        public level: string = '',
        public domain: {
            public: boolean,
            taxis: boolean,
            courierService: boolean,
            policyResearch: boolean,
            construction: boolean,
            safety: boolean,
            skillBuilding: boolean,
            advocacy: boolean,
            leadershipMentorship: boolean,
            conferenceSpeaker: boolean,
            academia: boolean,
            manufacturer2: boolean,
            iTSoftware: boolean,
            innovation: boolean,
            other: boolean,
        } = {
                public: false,
                taxis: false,
                courierService: false,
                policyResearch: false,
                construction: false,
                safety: false,
                skillBuilding: false,
                advocacy: false,
                leadershipMentorship: false,
                conferenceSpeaker: false,
                academia: false,
                manufacturer2: false,
                iTSoftware: false,
                innovation: false,
                other: false,
            },
        public otherAreas: string[] = [],
        public otherApplications: string = '',
        public otherDomains: string[] = [],
        public languages: string[] = [],
        public speakingExperience: string = '',
        public contactEmail: boolean = false,
        public email: string = '',
        public contactLinkedIn: boolean = false,
        public linkedIn: string = '',
        public contactTwitter: boolean = false,
        public twitter: string = '',
        public picture: string = '',
        public webpage: string = '',
        public signin: {
            option: string,
            slack: boolean,
            mailing: boolean
        } = {
                option: '',
                slack: false,
                mailing: false
            },
    ) { }

}


