import { ɵBlockUntilFirstOperator } from '@angular/fire';

export class Speaker {

    constructor(
        public id: string = '',
        public name: string = '',
        public position: string = '',
        public qualifications: string = '',
        public sector: {
            professionalDriver: boolean,
            professionalRider: boolean,
            plantOperator: boolean,
            conductor: boolean,
            captain: boolean,
            saccoManager: boolean,
            stageManager: boolean,
            clerk: boolean,
            courierProvider: boolean,
            driverInstructor: boolean,
            conductorInstructor: boolean,
            mechanic: boolean,
            civilEng: boolean,
            urban: boolean,
            trainer: boolean,
            leadandMentor: boolean,
            confSpeaker: boolean,
            policy: boolean,
            telphoneDev: boolean,
            autoManufacture: boolean,
            other: boolean,
        } = {
                professionalDriver: false,
                professionalRider: false,
                plantOperator: false,
                conductor: false,
                captain: false,
                saccoManager: false,
                stageManager: false,
                clerk: false,
                courierProvider: false,
                driverInstructor: false,
                conductorInstructor: false,
                mechanic: false,
                civilEng: false,
                urban: false,
                trainer: false,
                leadandMentor: false,
                confSpeaker: false,
                policy: false,
                telphoneDev: false,
                autoManufacture: false,
                other: false,
            },
        public otherSector: string = '',
        public bio: string = '',
        public region: string = '',
        public country: string = '',
        public city: string = '',
        public years: string = '',
        public level: string = '',
        
        public domain: {
            publicTransport: boolean,
            onlineTaxi: boolean,
            courierService: boolean,
            research: boolean,
            roads: boolean,
            safety: boolean,
            skills: boolean,
            advocacy: boolean,
            mentorship: boolean,
            speaker: boolean,
            academia: boolean,
            manufacturer: boolean,
            software: boolean,
            innovation: boolean,
            other: boolean,
        } = {
            publicTransport: false,
            onlineTaxi: false,
            courierService: false,
            research: false,
            roads: false,
            safety: false,
            skills: false,
            advocacy: false,
            mentorship: false,
            speaker: false,
            academia: false,
            manufacturer: false,
            software: false,
            innovation: false,
                other: false,
            },
        public otherAreas: string[] = [],
        public otherApplications: string = '',
        public otherDomains: string[] = [],
        public languages: string[] = [],
        public speakingExperience: string = '',
        public contactEmail: boolean = false,
        public email: string = '',
        public contactLinkedIn: boolean = false,
        public linkedIn: string = '',
        public contactTwitter: boolean = false,
        public twitter: string = '',
        public picture: string = '',
        public webpage: string = '',
        public signin: {
            option: string,
            slack: boolean,
            mailing: boolean
        } = {
                option: '',
                slack: false,
                mailing: false
            },
        public geoFeature: any = null
    ) { }

}


